version: 1.0.{build}
os: Visual Studio 2015
platform: Any CPU
init:
- git config --global core.autocrlf true
cache: packages -> **\packages.config
before_build:
- nuget restore
build:
  project: TestCoverageProject.sln
  verbosity: minimal
test:
  assemblies: '**\*.Tests.dll'